### PR TITLE
Postgres

### PR DESCRIPTION
**Pull request by foohooboo**
ABE: Postgres is already installed on the vagrant machine, and the database `quizrt` is already created. Therefore there are no changes needed (the django postgres user doesn't need to create a database because it already exists and django is the owner of quizrt). 
Do not run the below commands, as they are unnecessary, and could cause environment issues that would be a pain to debug.

If you really need to modify roles, for future reference, do:

1. Access the postgres command line: `sudo su - postgres` to become the postgres user.
Then you can run `psql quizrt` to access the database.
2. Run `ALTER ROLE django WITH CREATEDB;`
Don't forget the semicolon, because otherwise psql will ignore the command

-------------------------------------------------------------------------

FYI--
If you don't want to re-establish the vagrant machine then 
you'll need to 

`sudo apt-get install postgresql`

also, you'll need to, first, get into your psql database and then give the django user permission to create a database:

`psql db`
//note to the above command, you may need to add the tag '-U vagrant' if it cries at you.

`ALTER ROLE django WITH CREATEDB`

then i imagine that things will blow up in your face.  maybe. who knows.

### CODE REVIEW

**Comment by foohooboo** [comment]
@aposhiana the create mutation works, here's an example of how to execute it from the graphql page. 

`mutation{
  createUser(userData: {
    username: "whoopyG-money", 
    firstName: "whoopy",
    lastName: "goldberg",
    email: "whoopy@test.com",
    password: "meo12345"
  }){
    user{
      username
    }
    id
  }
}`

it looks kinda ugly posted here, so you should know that I new-lined the piss out of it.

**Comment by WhiteAbeLincoln** [comment]
@foohooboo There are some issues with this pull request. 

First, in base.py, we should not hard code the database options. They should be loaded from the environment
```python
 DATABASES = {
      'default': {
        'ENGINE': os.environ.get('DBENGINE'),
        'NAME': os.environ.get('DBNAME'),
        'USER': os.environ.get('DBUSER'),
        'PASSWORD': os.environ.get('DBPASSWORD'),
        'HOST': os.environ.get('DBHOST'),
        'PORT': os.environ.get('DBPORT'),
      }
```

Second, adding postgresql to the pip requirements should be unnecessary and will break things, since `postgresql` is not a python package.

Other than that it looks good. Once those changes are made we should be able to merge.

**Review by WhiteAbeLincoln — CHANGES_REQUESTED** [review]
@foohooboo There are some issues with this pull request. 

First, in base.py, we should not hard code the database options. They should be loaded from the environment. The .env file contains the correct defaults
```python
 DATABASES = {
      'default': {
        'ENGINE': os.environ.get('DBENGINE'),
        'NAME': os.environ.get('DBNAME'),
        'USER': os.environ.get('DBUSER'),
        'PASSWORD': os.environ.get('DBPASSWORD'),
        'HOST': os.environ.get('DBHOST'),
        'PORT': os.environ.get('DBPORT'),
      }
```

Second, adding postgresql to the pip requirements should be unnecessary and will break things, since `postgresql` is not a python package.

Also, we shouldn't have first and last name as separate fields in the database.
See: http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
and
https://www.w3.org/International/questions/qa-personal-names

I think usernames should be unique, since they'll be how users are identified and will be used as a url slug. I'm just going off of the github model though.

so users table should have at minimum:
```sql
id INT PRIMARY KEY,
email CHARACTER VARYING(255) NOT NULL,
name CHARACTER VARYING(255),
username CHARACTER VARYING(255) NOT NULL UNIQUE,
```

Other than that it looks good. Once those changes are made we should be able to merge.

**Comment by WhiteAbeLincoln** [comment]
Also, we shouldn't have first and last name as separate fields in the database.
See: http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
and
https://www.w3.org/International/questions/qa-personal-names

**Comment by aposhiana** [comment]
This is a good start.  I think we are good to merge.  @WhiteAbeLincoln if we change how the names are stored I say we keep it simple and have one name field.  I think it is ok for now though because internationality isn't part of the MVP.

**Review by aposhiana — APPROVED** [review]
I say we merge it.  I can do another pull requests with the other parts of the schema and any necessary improvements with the User models and schema.

**Review by WhiteAbeLincoln — APPROVED** [review]

**Pull request merged**
